### ISSUE TITLE
Updating the chat title string in defaults: some options not updating!

### ISSUE THREAD

**Issue by Marcquito** [ouun/zammad-wp#1]
First of all, thank you so much for the fantastic work. This integration is incredible! 

My issue is with the defaults when configuring/modifying the chat box within wp-config.php. For example, the color easily updates as a default color, but the title string and flat boolean do not seem to update. 

Example:
            'title'         => 'Need a hand?',
            'background'    => '#00adef;',  **_<- This is the only one that works._** 
            'flat'          => true

Any insight on what could be wrong? Thank you for the help!

**Comment by ouun** [comment]
Hi @Marcquito,

thanks for the positive feedback.
Sounds like you are trying to add the code to the wrong file `wp-config.php`. The only reason why it seems to work for you is, that the scripts tries to find the "primary" color of your website automatically. This is for sure misleading you...

`wp-config.php` is only used to define global variables. All other code should either go into your themes `function.php` or you add a new file in `/mu-plugins`. 

Kind regards

**Comment by Marcquito** [comment]
Thanks for the reply @ouun !
I appreciate the clarification. I moved the code into the functions.php of the theme and I seem to get the same result. Here is how it looks: 
`/* Zammad Helpdesk Chat */
add_action('admin_init', function () {
    if (function_exists('zammad_register_chat')) {
        // Logged in user at least with editor role, load chat with topic '2'
        if (is_user_logged_in() && current_user_can('edit_posts')) {
            zammad_register_chat( 2, [
                'formFallback'  		=> true,
                'buttonClass'   		=> 'button action',
                'target'        		        => '$("#wpbody")'
            ] );
        }
    }
});
add_filter('zammad_wp:chat:defaults', function ($defaults) {
    return wp_parse_args(
        [
            'debug' 					        => false,
			'title' 					=> 'My New Chat Title!',
			'background'				=> '#333',
			'flat'						=> true
        ],
        $defaults
    );
});
`
As with the previous result, I'm able to change the background color here, but none of the other filters seem to work. Just to be clear though, the chat still functions beautifully outside of that! What else do you think I could have done incorrectly? I'm also including a few screenshots if that helps. 👍 

<img width="486" alt="chat-code" src="https://user-images.githubusercontent.com/5797508/95605759-66d26980-0a27-11eb-885c-defc228ba667.png">
<img width="344" alt="chat-title" src="https://user-images.githubusercontent.com/5797508/95605762-676b0000-0a27-11eb-8d54-ebb5235e8db8.png">

**Comment by ouun** [comment]
OK, I will need to double-chack the `zammad_wp:chat:defaults` filter, but you should be able to remove the whole block and just add the array keys and values to the `zammad_register_chat` function above. That works for sure, I am using it on live sites as well. So you will end with something like this:

```
add_action('admin_init', function () {
    if (function_exists('zammad_register_chat')) {
        // Logged in user at least with editor role, load chat with topic '2'
        if (is_user_logged_in() && current_user_can('edit_posts')) {
            zammad_register_chat( 2, [
                'buttonClass' => 'button action',
                'target' => '$("#wpbody")',
                'formFallback' => true,
                ' background' => '#333',
                'flat' => true,
                'tiitle' => 'My new chat title!'
            ] );
        }
    }
});
```

**Comment by Marcquito** [comment]
A HUGE thank you for the great response. Not long before your last reply, I did discover 'chatTitle' to be the correct filter. The code update definitely works. Thanks again for the powerful integration!

**Comment by ouun** [comment]
Glad that worked! :)
