### ISSUE TITLE
chat error || Chat: need chatId as option!

### ISSUE THREAD

**Issue by sbu-WBT** [ouun/zammad-wp#12]
I installed the plugin via wordpress.

I added those like described in [Embed-Live-Chat](https://github.com/ouun/zammad-wp/wiki/Embed-Live-Chat) to `wp-content/themes/hestia/functions.php`.

```php
add_filter('zammad_wp:chat:defaults', function ($defaults) {
    return wp_parse_args(
        [
            'chatId' => 1,
            'background' => '#00B4FF',
        ],
        $defaults
    );
});

add_action('init', function () {
        if (function_exists('zammad_register_chat')) {
            zammad_register_chat($chatId, $args);
        }
    });
```

We have also the chat enabled:
![image](https://user-images.githubusercontent.com/64100880/117643605-df013900-b188-11eb-8077-29035b7f8317.png)

But we get the error `chat error || Chat: need chatId as option!` inside the browser console.

If we look at the `chatOptions` is also set there:

![image](https://user-images.githubusercontent.com/64100880/117643822-1cfe5d00-b189-11eb-8eda-1cb089d46512.png)

Wordpress Version 5.7.1

**Comment by sbu-WBT** [comment]
Ah danke, das hat geholfen. Der Fehler ist weg. (Auch wenn ich den Chat nirgends sehen kann^^)

**Comment by ouun** [comment]
@sbu-WBT hat es geklappt? In der Standardeinstellung wird der Chat nur angezeigt wenn auch ein Agent in Zammad online ist. Du kannst zusätzlich einen Fallback auf ein Formular setzen.
