### ISSUE TITLE
Update plugin from within Wordpress

### ISSUE THREAD

**Issue by enoch85** [ouun/zammad-wp#18]
Just found this, just what I need!

On mobile now so haven't tested, but does this upgrade from within the plugin manager @ Wordpress?

Thanks for making this!

**Comment by ouun** [comment]
Hi @enoch85. Glad it is useful for you. However currently this is installable as a Composer package and not yet in the  WordPress.org repository. However you can use the [Git Updater Plugin](https://git-updater.com/).  I prepared this package  to be compatible with it and in combination the WordPress update system should just work fine with Github as source.

**Comment by enoch85** [comment]
Thanks!
