### ISSUE TITLE
Wordpress integration error in ZammadAPIClient

### ISSUE THREAD

**Issue by bidikov** [ouun/zammad-wp#23]
Hi, 
The plugin is the latest version 0.8.3
Zammad is also latest

We are using the html forms integrstion everything worked perfectly but now we see in the wordpress error log:

PHP Fatal error:  Uncaught TypeError: Return value of ZammadAPIClient\\HTTPClient::request() must be an instance of Psr\\Http\\Message\\ResponseInterface, null returned in .../wp-content/plugins/zammad-wp-1/vendor/zammad/zammad-api-client-php/src/HTTPClient.php:166\n
Stack trace:\n
#0 .../wp-content/plugins/zammad-wp-1/vendor/zammad/zammad-api-client-php/src/Client.php(79): ZammadAPIClient\\HTTPClient->request('GET', 'users/search', Array)\n
#1 .../wp-content/plugins/zammad-wp-1/vendor/zammad/zammad-api-client-php/src/Client.php(110): ZammadAPIClient\\Client->request('GET', 'users/search', Array)\n

We thought that maybe it's a token issue so we have regenerated a token and updated wp-config.php but still the same error...
Also on the Zammad admin i see that "Last used" field for the HTTP token is blank while the old token last use stops "09/30/2021"

Please advice on how to debug this...
Also, it whould help if you can document what token permisions are required for the WP plugin...

**Comment by ouun** [comment]
@bidikov I am not able to replicate that. Did you find a solution in the meantime?

**Comment by bidikov** [comment]
Finnaly got some time to look into this over the holidays...

It seems that the error was tracked into connectivity problem to the zammad instance (firewall problem returning zero bytes responses) - but errors where somehow reported as bad packet in communication...

The stack traces where quite misleading but we can declare this as non relevant any more...
