### ISSUE TITLE
Nothing happens when I click on "Create Zammad Ticket" button

### ISSUE THREAD

**Issue by Brendyyyp** [ouun/zammad-wp#27]
Hi @ouun,

I've a little problem. Nothing happens when I click on the "Send Email" or "Create Zammad Ticket" button.

I read the thread of this issue "Plugin not working with HTML Forms
#4". I have v0.8.3 of the Zammad for WordPress plugin and I also set the Debug mode, but I didn't see any errors related to the plugin. I checked the console and I have no PHP errors related to your plugin. I have deleted many plugins to see if there is an incompatibility issue but nothing, I can't get the "Create Zammad Ticket" button to work.

Also, I have correctly noted my ZAMMAD_URL / ZAMMAD_USERNAME and ZAMMAD_PASSWORD, since the chat is working correctly and I am retrieving the data in my Zammad back office.

Can you help me further to find out what is causing the problem, please? I can give you temporary access to my staging site if you want to take a closer look.

Can you help me find out what is causing the problem?

Thanks to you, have a nice day!

**Comment by ouun** [comment]
Hi @Brendyyyp,
sorry that I am getting back to you so late, but life and work are quite buzy at the moment. 
I might be able to have a look next week, please send your details at  `philipp     at      ouun.io`.

Kind regards

**Comment by Brendyyyp** [comment]
Hi @ouun,

No problem, I totally understand and thank you for your time!
Finally it works, there must be an incompatibility with another plugin. However I can't get the tickets in Zammad. I looked at the console and I have this error:

> HTML Forms: failed to parse AJAX response.
> Error: "SyntaxError: Unexpected token * in JSON at position 0"

I will contact HTML Forms theme support to see if they can help me with this as well. Maybe you will have the answer too.

I'll send you a summary of my problem and the login information to your email address.

Thanks for your help!

Kind regards

**Comment by ouun** [comment]
@Brendyyyp I have not heard back from you, therefore closing the ticket now. Feel free to reopen if the issue persists.
