### ISSUE TITLE
PHP 8.0x compatibility

### ISSUE THREAD

**Issue by Blackskyliner** [ouun/zammad-wp#38]
As newer Wordpress Versions 6.1.x are running fine with PHP 8.1 the Plugin should also support of the mentioned version of PHP. As the current constraints limits the usability of this Plugin to old Wordpress Installations running on EOLed PHP 7.4.

The used WP_Mock uses the constraint `"php": ">=7.3 < 9.0"` in the composer file which we could also use as depending library.

**Comment by ouun** [comment]
@Blackskyliner I agree. Please feel free to create a PR for this and I will merge it. Thanks!

**Comment by ouun** [comment]
@Blackskyliner as I am releasing v0.9.1 anyways, I just did the change myself. However thanks a lot for the hint.
