### ISSUE TITLE
Embed Form problem 

### ISSUE THREAD

**Issue by RAFd3v** [ouun/zammad-wp#41]
If I try to embed the form like in the wiki I only see the code. Not the form. What’s my failure? In which kind I need to embed it? Sorry pretty new to WordPress.

**Comment by ouun** [comment]
@RAFd3v  I appreciate your interest in this package.
As you've seen, it requires a basic understanding of PHP and how to implement it. I am sorry, but this is beyond the scope of the support I can provide. I recommend that you get a developer to help you.

Best regards
