### ISSUE TITLE
@F3rr021 just tested it on a freh install and it works as expected. Please go sure that you [download the latest release ](https://github.com/ouun/zammad-wp/releases/latest/download/zammad-wp.zip)and not just the files from the repository if you are not using Composer. The release files contain a `/vendor` folder which is required.

### ISSUE THREAD

**Issue by F3rr021** [ouun/zammad-wp#43]
[25-Jul-2024 15:45:16 UTC] PHP Fatal error:  Uncaught RuntimeException: Missing option "url" in /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/HTTPClient.php:55
Stack trace:
#0 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/Client.php(52): ZammadAPIClient\HTTPClient->__construct(Array)
#1 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/classes/Zammad.php(73): ZammadAPIClient\Client->__construct(Array)
#2 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/classes/Zammad.php(55): ZammadWp\Zammad->client()
#3 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/functions/hf-plugin-integration.php(128): ZammadWp\Zammad->__construct(Array)
#4 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(324): zammad_hf_process_form_action(Array, Object(HTML_Forms\Submission), Object(HTML_Forms\Form))
#5 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /home/eajijifb/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/eajijifb/public_html/wp-content/plugins/html-forms/src/class-forms.php(300): do_action('hf_process_form...', Array, Object(HTML_Forms\Submission), Object(HTML_Forms\Form))
#8 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(324): HTML_Forms\Forms->listen_for_submit('')
#9 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 /home/eajijifb/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /home/eajijifb/public_html/wp-settings.php(700): do_action('init')
#12 /home/eajijifb/public_html/wp-config.php(96): require_once('/home/eajijifb/...')
#13 /home/eajijifb/public_html/wp-load.php(50): require_once('/home/eajijifb/...')
#14 /home/eajijifb/public_html/wp-admin/admin-ajax.php(22): require_once('/home/eajijifb/...')
#15 {main}
  thrown in /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/HTTPClient.php on line 55          
    @F3rr021 just tested it on a freh install and it works as expected. Please go sure that you [download the latest release ](https://github.com/ouun/zammad-wp/releases/latest/download/zammad-wp.zip)and not just the files from the repository if you are not using Composer. The release files contain a `/vendor` folder which is required.

Closing this as I expect it to work. If it does not, please feel free to re-open.

_Originally posted by @ouun in https://github.com/ouun/zammad-wp/issues/42#issuecomment-2242922407_

**Comment by F3rr021** [comment]
Hello, thank you for your response, in addition to what you do with this pluing. But I still have the same problem. I have downloaded from the link you reference, I have the configuration of define('ZAMMAD_URL', 'https://pqrs.importadoraevolucion.com');
define('ZAMMAD_HTTP_TOKEN', 'my token'); and i can see:
![Captura de pantalla 2024-07-25 093509](https://github.com/user-attachments/assets/e587c4c1-e62a-4c61-af54-99ecb5f55aa1)
![Captura de pantalla 2024-07-25 102718](https://github.com/user-attachments/assets/b917ea87-367a-4c4b-a7ed-2c18b0b59739)
![Captura de pantalla 2024-07-25 102737](https://github.com/user-attachments/assets/9849a248-7937-4300-a834-5b116f3ea68c)

Zammad Group *
Priority Ticket *
Ticket Status *
Ticket Subject
Message *

but when I try to create the ticket using the form it still shows that the url is not defined and hence the other errors. I understand that the connection is fine, because I can see the groups and so on, but when I try to create the ticket from the form, it does not find it. Please, can you help me? the vendor folder is there, I don't use composer.

This is the log error:

[25-Jul-2024 15:45:16 UTC] PHP Fatal error: Uncaught RuntimeException: Missing option "url" in /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/HTTPClient.php:55
Stack trace:
#0 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/Client.php(52): ZammadAPIClient\HTTPClient->__construct(Array)
#1 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/classes/Zammad.php(73): ZammadAPIClient\Client->__construct(Array)
#2 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/classes/Zammad.php(55): ZammadWp\Zammad->client()
#3 /home/eajijifb/public_html/wp-content/plugins/zammad-wp/includes/functions/hf-plugin-integration.php(128): ZammadWp\Zammad->__construct(Array)
#4 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(324): zammad_hf_process_form_action(Array, Object(HTML_Forms\Submission), Object(HTML_Forms\Form))
#5 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /home/eajijifb/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/eajijifb/public_html/wp-content/plugins/html-forms/src/class-forms.php(300): do_action('hf_process_form...', Array, Object(HTML_Forms\Submission), Object(HTML_Forms\Form))
#8 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(324): HTML_Forms\Forms->listen_for_submit('')
#9 /home/eajijifb/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#10 /home/eajijifb/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /home/eajijifb/public_html/wp-settings.php(700): do_action('init')
#12 /home/eajijifb/public_html/wp-config.php(96): require_once('/home/eajijifb/...')
#13 /home/eajijifb/public_html/wp-load.php(50): require_once('/home/eajijifb/...')
#14 /home/eajijifb/public_html/wp-admin/admin-ajax.php(22): require_once('/home/eajijifb/...')
#15 {main}
thrown in /home/eajijifb/public_html/wp-content/plugins/zammad-wp/vendor/zammad/zammad-api-client-php/src/HTTPClient.php on line 55

**Comment by ouun** [comment]
Closed as dupicate of https://github.com/ouun/zammad-wp/issues/42

**Comment by ouun** [comment]
Closed as dupicate of https://github.com/ouun/zammad-wp/issues/42
