### ISSUE TITLE
Line breaks in the HF Forms submission message are not parsed correctly

### ISSUE THREAD

**Issue by terdinatore** [ouun/zammad-wp#45]
I have recently discovered that messages submitted through my website to my Zammad instance do not have any line breaks. Even though there clearly are line breaks in the messages when inspecting the HF Forms submission in the WP Admin Dashboard. 

So, I invested some time to figure out what is happening here. The culprit seems to be the `content-type` used in the API request. When set to `text\html` line breaks are not parsed, but when using `text\plain` or no `content-type` at all the message is parsed correctly.

Assuming that no one actually has website users filling in forms in HTML, and thus the only expected message content is plain text, I would like to suggest changing to `content-type: text\plain`

**Comment by terdinatore** [comment]
Nevermind, I realized this has been fixed in the newest version already. Closed

**Comment by ouun** [comment]
@terdinatore thank you for bringing this up. Where is this fixed? In Zammad, Zammad WP or HF Forms?

**Comment by terdinatore** [comment]
I am using this plugin on two websites of mine and at first one of them on HTML Forms 1.3.27 sent `TEST\r\nNEWLINE` as message and the other on 1.3.32 sent `TEST<br />NEWLINE`.

For `\r\n`, `text/plain` is needed and for `<br />`, `text/html` is needed in order for the breaks to be correctly parsed. 

Now, I have updated both HTML Forms to the newest 1.4.2 version and messages from both websites use `<br />`. 
I can't pinpoint the exact change in the source (I think HTML Forms isn't even on GH and has no changelog), but from the observations above, I would say that this is an 'un-breaking' change in HTML Forms with some certainty.

Hope that helps.
