### ISSUE TITLE
HTTP Token Best Practice - Which permissions are needed?

### ISSUE THREAD

**Issue by terdinatore** [ouun/zammad-wp#5]
Below I wrote down / summarized, how I think in best practice an HTTP Token should be generated.

1.  Login to your Zammad instance with an administrator account.
2. Under _Settings ⇾ Manage ⇾ Roles_ create a new role, I called that role _Connector_
3. The new _Connector_ role needs the following grants: `Manage Groups, Manage Tags, Access to Chat, Access to Agent Tickets, Manage Access Tokens and Manage Notifications`
4. At the `Access to Agent Tickets` give the role only the permission to create tickets for every group and nothing else. This is for two reasons. Firstly, this way you can make sure that if the token gets leaked no one can read the tickets on your instance, secondly this way users that have the _Connector_ role do not show up in Zammad as they cannot have tickets assigned to them.
5. Now create a user that we for instance could call _Website Connector_. Assign this user the _Connector_ permissions and create access to all groups.
6. Click on the Action Menu on the far right of the Users table and click _View from user's perspective_
7. Open the new users profile by clicking on the icon with its initials on the lower left and choosing Profile.
8. Disable all notifications for this user.
9. Now under _Token Access_ create a new token that has permissions to all resources that the roles except `Manage Token Access` and `Manage Notifications`. Give the token a name and set a suiting expiry date for the token. Click Create. Copy the token and close the window. Switch back to the administrator account.

@ouun What do you think? 
Are there any other permissions (not) needed? 
Could there be a way to structure the plugin without needing `Manage Groups`and `Manage Tags`?
Also, is there any advantage in using an OAuth token instead of HTTP?

**Comment by ouun** [comment]
Thanks for this, @terdinatore. I am sure it will be helpfukl for others.
It really depends on your needs and honestly the only authentification method I did not use with Zammad is 'HTTP Token'.
I prefere to add an Application in Zammad under `Settings -> API -> Applications (OAuth Authentication)` and to use that in favor. Also no extra user or role is required, as far as I am aware of. But it is also a while ago that I set up the last connection, it is running smoothely as it is.
