### ISSUE TITLE
Integration zammad 4.0.0 an WP 5.7

### ISSUE THREAD

**Issue by DeamonMV** [ouun/zammad-wp#9]
Hello

I have install zammad-wp as a plugin. Downloaded a latest version as zip archive and put in plugins/zammad-wp folder. Made correct permissions and owner.

Then I activated plugin. Into `wp-config.php` put `define('ZAMMAD_URL', 'https://my-zammad.com')`

But nothing happened. What should be the next step? On the front page nothing has been add

**Comment by ouun** [comment]
Hi @DeamonMV,
did you see the Wiki? https://github.com/ouun/zammad-wp/wiki
You need to also addd your access details.

**Comment by DeamonMV** [comment]
Hi.

Thanks. Looks like we solve our problem.

Thank you for the you replay.
